### PR TITLE
Create Modules subdirectory in cmake

### PR DESCRIPTION
**Pull request by mark0n**
Let's follow CMake conventions. See for example `/usr/share/cmake-x.y/` or the [CMake Wiki](https://cmake.org/Wiki/CMake:How_To_Find_Libraries#Using_external_libraries_that_CMake_doesn.27t_yet_have_modules_for).

### CODE REVIEW

**Comment by mark0n** [comment]
`EPICSMain.cpp` and `EPICSVersion.cmake.in` should probably go into `/usr/share/cmake-x.y/Templates`. Not sure how to include them from there, though.

**Comment by mark0n** [comment]
OK, I have moved `EPICSMain.cpp` and `EPICSVersion.cmake.in` into `/usr/share/cmake-x.y/Templates`. Not sure if there is a better way to include them from there.

**Comment by mark0n** [comment]
OK, I think I finally got it right. The examples build as well as my device support module.

**Comment by mdavidsaver** [comment]
I wasn't immediately enthused about reorganizing the source tree.  I'll agree to it once though.  You'll need to update the README:

```cmake
list(APPEND CMAKE_MODULE_PATH ${CMAKE_SOURCE_DIR}/c4e/cmake)
```

It's probably time to start a changelog as well.

Also, using ```/usr/share/cmake-x.y``` for the deb packaging is going to impose an unnecessarily strict dependence on cmake version.  However, I checked and unfortunately there really are no other paths searched.  So you either need to use appropriately tight Depends and possibly Build-Depends, or use a trigger to inspect the cmake version and copy into the right place a la. dh_python.

**Comment by mark0n** [comment]
Sorry, I actually meant to say `cmake/Templates` in my second and third comment.

For the Debian package I was actually intending to install the cmake folder into `/usr/lib/epics`. Please see https://github.com/mark0n/cmake4epics/tree/debian for a first try in packaging it.

**Comment by mark0n** [comment]
Good catch with the README. I just fixed this.

**Pull request merged**
